### ISSUE TITLE
Our mistakes

### ISSUE THREAD

**Issue by teamdodo** [Dogeek/isaac-debug-helper#3]
First mistake: we had written functions.py twice, once naming it main.py. Obviously the software does not work, also in your repository because of our pull request. Now we have updated the source in our repository.
Second mistake: pull request included changes to readme.md, probably you should restore your old readme.md (if possible add link to our fork?)

**Comment by sbordeyne** [comment]
I'll do that. Thanks, I reviewed the PR hastily earlier, I had no time to test it.

**Comment by sbordeyne** [comment]
Created and merged the PR. Thanks for your contributions, I've not worked on this project in ages, because I left the Isaac modding scene after finishing all the code for TBOI:Stillbirth content pack 1. 

The new readme is fine (in your latest commit). Maybe I'll add a sprite editor for isaac with its custom palettes. Maybe even a code editor, and publisher using tboi's tool. Sometime. Later.

**Comment by teamdodo** [comment]
Thank you sir, we had made a mess. We are in your same situation: we are using the tool to create a TBOI mod (and by the way we are looking for experienced coders). When you will start working on new features of Isaac Modding Helper Tool we will be happy to help you.

**Comment by sbordeyne** [comment]
I may (or may not) work on this again in the future. I'm wrapping up a project right nw, and I have some free time. Your PR actually made me remember I made this thing. I'm glad you're enjoying this tool, I made it really quickly when working on stillbirth, and that was part of the mod's repo for a while until I decided it'd be best to let it have its own repo. 

If you think of any features you think would be helpful in developing mods for isaac, just open up a new issue. I love checking things off of lists.
